name: gossip_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  animated_text_kit: ^4.2.1
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  cloud_firestore: ^2.2.2
  flutter_svg: ^0.22.0
  image_picker: ^0.8.1+2
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/main_top.png
    - assets/images/main_bottom.png
    - assets/icons/chat.svg
    - assets/icons/login.svg
    - assets/icons/signup.svg
    - assets/icons/facebook.svg
    - assets/icons/google-plus.svg
    - assets/icons/twitter.svg